src/Entity/Commande.php
<?php

namespace App\Entity;

use App\Repository\CommandeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommandeRepository::class)
 */
class Commande
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $numero;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $rue;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $complement;

    /**
     * @ORM\Column(type="integer")
     */
    private $montant;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $horraireLivraison;

    /**
     * @ORM\Column(type="integer")
     */
    private $code_postal;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ville;

    /**
     * @ORM\ManyToOne(targetEntity=Client::class, inversedBy="commandes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $client;


    /**
     * @ORM\OneToMany(targetEntity=LigneCommande::class, mappedBy="commande")
     */
    private $ligneCommandes;

    /**
     * @ORM\ManyToOne(targetEntity=StatutCommande::class, inversedBy="commandes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $statut;

    /**
     * @ORM\ManyToOne(targetEntity=Restaurant::class, inversedBy="commandes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $restaurant;

    /**
     * @ORM\ManyToOne(targetEntity=Livreur::class, inversedBy="commandes")
     */
    private $livreur;

    public function __construct()
    {
        $this->ligneCommandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNumero(): ?string
    {
        return $this->numero;
    }

    public function setNumero(string $numero): self
    {
        $this->numero = $numero;

        return $this;
    }

    public function getRue(): ?string
    {
        return $this->rue;
    }

    public function setRue(string $rue): self
    {
        $this->rue = $rue;

        return $this;
    }

    public function getComplement(): ?string
    {
        return $this->complement;
    }

    public function setComplement(?string $complement): self
    {
        $this->complement = $complement;

        return $this;
    }

    public function getMontant(): ?int
    {
        return $this->montant;
    }

    public function setMontant(int $montant): self
    {
        $this->montant = $montant;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getHorraireLivraison(): ?\DateTimeInterface
    {
        return $this->horraireLivraison;
    }

    public function setHorraireLivraison(?\DateTimeInterface $horraireLivraison): self
    {
        $this->horraireLivraison = $horraireLivraison;

        return $this;
    }

    public function getCodePostal(): ?int
    {
        return $this->code_postal;
    }

    public function setCodePostal(int $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): self
    {
        $this->client = $client;

        return $this;
    }

    /**
     * @return Collection|LigneCommande[]
     */
    public function getLigneCommandes(): Collection
    {
        return $this->ligneCommandes;
    }

    public function addLigneCommande(LigneCommande $ligneCommande): self
    {
        if (!$this->ligneCommandes->contains($ligneCommande)) {
            $this->ligneCommandes[] = $ligneCommande;
            $ligneCommande->setCommande($this);
        }

        return $this;
    }

    public function removeLigneCommande(LigneCommande $ligneCommande): self
    {
        if ($this->ligneCommandes->removeElement($ligneCommande)) {
            // set the owning side to null (unless already changed)
            if ($ligneCommande->getCommande() === $this) {
                $ligneCommande->setCommande(null);
            }
        }

        return $this;
    }

    public function getStatut(): ?StatutCommande
    {
        return $this->statut;
    }

    public function setStatut(?StatutCommande $statut): self
    {
        $this->statut = $statut;

        return $this;
    }

    public function getRestaurant(): ?Restaurant
    {
        return $this->restaurant;
    }

    public function setRestaurant(?Restaurant $restaurant): self
    {
        $this->restaurant = $restaurant;

        return $this;
    }

    public function getLivreur(): ?Livreur
    {
        return $this->livreur;
    }

    public function setLivreur(?Livreur $livreur): self
    {
        $this->livreur = $livreur;

        return $this;
    }
}

src/Form/CommandeType.php
<?php

namespace App\Form;

use App\Entity\Commande;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommandeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('rue')
            ->add('complement')
            ->add('code_postal')
            ->add('ville', null, [
                'attr' => ['list' => 'listeville']
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Commande::class,
        ]);
    }
}

src/Controller/CommandeController.php
<?php

namespace App\Controller;

use App\Api\VilleApi;
use App\Entity\Commande;
use App\Entity\LigneCommande;
use App\Form\CommandeType;
use App\Repository\CommandeRepository;
use App\Repository\PlatRepository;
use App\Repository\RestaurantRepository;
use App\Repository\StatutCommandeRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @IsGranted("ROLE_USER")
 * @Route("/commande")
 */
class CommandeController extends AbstractController
{
    /**
     * @Route("/", name="commande_index", methods={"GET"})
     */
    public function index(CommandeRepository $commandeRepository): Response
    {
        return $this->render('commande/index.html.twig', [
            'commandes' => $commandeRepository->findAll(),
        ]);
    }

    /**
     * @Route("/valider", name="commande_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager, SessionInterface $session, PlatRepository $platRepository, RestaurantRepository $restaurantRepository, StatutCommandeRepository $statutRepository): Response
    {
        $client = $this->getUser()->getClient();
        $villes = VilleApi::getVilles();
        $commande = new Commande();

        if(!$session->has('panier'))
        {
            $session->set('panier', []);
        }

        $panier = $session->get('panier');
        $panierWhithData = [];

        foreach ($panier as $id => $quantite) {
            $panierWhithData[] = [
                'plat' => $platRepository->find($id),
                'quantite' => $quantite
            ];
        }

        $total=300;

        foreach ($panierWhithData as $item) {
            $totalByPlat=$item['plat']->getPrix() * $item['quantite'];
            $total+= $totalByPlat;
        }

        $form = $this->createForm(CommandeType::class, $commande);
        $form->handleRequest($request);

        $restaurant = $restaurantRepository->find($panierWhithData[0]['plat']->getRestaurant()->getId());
        
        if ($form->isSubmitted() && $form->isValid() && $form->getData()->getVille() == $restaurant->getVille()) {
            $commande->setNumero(rand(0, 1000000));
            $commande->setMontant($total);
            $commande->setClient($client);
            $commande->setDate(new \DateTime());
            $commande->setRestaurant($restaurant);
            $commande->setStatut($statutRepository->findOneBy(['nom'=>'en attente']));

            $entityManager->persist($commande);
            $entityManager->flush();
            foreach ($panierWhithData as $plat) {
                $ligneCommande = new LigneCommande();
                $ligneCommande->setCommande($commande);
                $ligneCommande->setPlat($plat['plat']);
                $ligneCommande->setQuantite($plat['quantite']);
                $plat['plat']->setStock($plat['plat']->getStock()-$plat['quantite']);

                $entityManager->persist($ligneCommande);
                $entityManager->flush();
            }

            $session->set('panier', []);

            return $this->redirectToRoute('commande_merci', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('commande/new.html.twig', [
            'commande' => $commande,
            'form' => $form,
            'client' => $client,
            'villes' =>$villes
        ]);
    }

    /**
     * @Route("/{id<\d+>}", name="commande_show", methods={"GET"})
     */
    public function show(Commande $commande): Response
    {
        return $this->render('commande/show.html.twig', [
            'commande' => $commande,
        ]);
    }

    /**
     * @Route("/merci", name="commande_merci", methods={"GET"})
     */
    public function merci(CommandeRepository $commandeRepository): Response
    {
        return $this->render('commande/merci.html.twig', [
            'commandes' => $commandeRepository->findAll(),
        ]);
    }
}

templates/commande/_form.html.twig
<div class="form">
	<h1>Entrer l'adresse de livraison</h1>
	{{ form_start(form) }}

	<div>
		{{ form_label(form.rue, "Rue :")}}
		{{ form_widget(form.rue, {'attr':{'value':client.rue}})}}
	</div>

	<div>
		{{ form_label(form.complement, "Complement :")}}
		{{ form_widget(form.complement, {'attr':{'value':client.complement}})}}
	</div>
	<div>
		{{ form_label(form.code_postal, "Code postal :")}}
		{{ form_widget(form.code_postal, {'attr':{'value':client.codePostal}})}}
	</div>
	<div>
		{{ form_label(form.ville, "Ville :")}}
		{{ form_widget(form.ville, {'attr':{'value':client.ville}})}}
		<datalist id="listeville">
		{% for ville in villes %}
			<option value="{{ville.nom}}">{{ville.nom}}</option>
		{% endfor %}
	</datalist>
	</div>

	<button class="btn" type="submit">{{ button_label|default('Valider') }}</button>


	{{ form_end(form) }}
</div>

templates/commande/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commande index{% endblock %}

{% block body %}
    <h1>Commande index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Numero</th>
                <th>Rue</th>
                <th>Complement</th>
                <th>Montant</th>
                <th>Date</th>
                <th>HorraireLivraison</th>
                <th>Code_postal</th>
                <th>Ville</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for commande in commandes %}
            <tr>
                <td>{{ commande.id }}</td>
                <td>{{ commande.numero }}</td>
                <td>{{ commande.rue }}</td>
                <td>{{ commande.complement }}</td>
                <td>{{ commande.montant }}</td>
                <td>{{ commande.date ? commande.date|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ commande.horraireLivraison ? commande.horraireLivraison|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ commande.codePostal }}</td>
                <td>{{ commande.ville }}</td>
                <td>
                    <a href="{{ path('commande_show', {'id': commande.id}) }}">show</a>
                    <a href="{{ path('commande_edit', {'id': commande.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('commande_new') }}">Create new</a>
{% endblock %}

templates/commande/merci.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commande index
{% endblock %}

{% block body %}
	<div class="commande-merci">
		<h2>Merci pour votre commande</h2>
		<p>Vous pouvez suivre l'état de votre commande dans votre compte ou en cliquant sur le bouton en-dessous</p>
		<button>
			<a href="{{path('client_index')}}">Voir ma commande</a>
		</button>
	</div>

	<style>
		.commande-merci {
			width: 800px;
			margin: 50px auto;
			text-align: center;
		}
		.commande-merci h2 {
			margin: 10px;
		}
		.commande-merci p {
			margin: 10px;
		}
		.commande-merci button {
			padding: 10px;
			background-color: #acace7;
			border: 2px solid #acace7;
			border-radius: 10px;
		}
		.commande-merci button a {
			text-decoration: none;
			color: white;
		}
	</style>

{% endblock %}

templates/commande/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Commande
{% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/form/form.css') }}">
{% endblock %}

{% block body %}

	{{ include('commande/_form.html.twig', {'client': client}) }}    

{% endblock %}

templates/commande/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commande
{% endblock %}

{% block body %}


	<h1 class="detailCommande-client">Detail Commande:
		{{commande.numero}}</h1>

	<div class="adresseLivraison-client">
		<h3>Adresse de livraison</h3>
		<p>{{commande.rue}}</p>
		{% if commande.complement %}
			<p>{{commande.complement}}</p>
		{% endif %}
		<p>{{commande.codePostal}}</p>
		<p>{{commande.ville}}</p>
	</div>

	<div class="compositonCommande-client">
		<section>
			<h3>Composition de la commande</h3>
			<table>
				<thead>
					<th>Photo</th>
					<th>Nom</th>
					<th>Prix</th>
					<th>Quantité</th>
				</thead>
				<tbody>
					{% for ligneCommande in commande.ligneCommandes %}
						<tr>
							<td><img src="{{asset("images/plat/"~ ligneCommande.plat.photo)}}" alt=""></td>
							<td>{{ligneCommande.plat.nom}}</td>
							<td>{{ligneCommande.plat.prix / 100}}</td>
							<td>{{ligneCommande.quantite}}</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</section>
	</div>

{% endblock %}